### ISSUE TITLE
Rendering issue when multiple <table> are contained in a `overflow: auto;` div

### ISSUE THREAD

**Issue by kuanyui** [mkoryak/floatThead#478]
# Related Issue
https://github.com/mkoryak/floatThead/issues/242

# Environment
- `floatThead` version: 2023-03-10 so far, latest stable `2.2.4` (via CDN)
- Chromium 110, Firefox 110 (Both browser has exactly the same rendering issue)

# Description
There are multiple tables needed to be placed under a scrollable container element, but if do so, `floatThead` will cause  rendering a mass. No matter set `options.position` to `fixed` or `absolute`, both one has respective issue. See the JSFiddle and this video: 

JSFiddle: http://jsfiddle.net/azazabc123/ap8or01s/16/

> *NOTE: Actually this JSFiddle is forked from this comment https://github.com/mkoryak/floatThead/issues/242#issuecomment-139284915:
>> @mkoryak: There was a bug with absolute positioning that I just fixed, see updated fiddle:
>> http://jsfiddle.net/f0rjzqL9/3/
>>
>> note that this fix only exists on master at this time.
>
> But the bug seems still exists?
>

https://user-images.githubusercontent.com/1370070/224236073-46275165-5906-431a-a345-8ea21881094d.mp4

**Comment by mkoryak** [comment]
Thank you for taking the time to write up this issue. I will take a look at
it in a few hours when I actually wake up :)

**Comment by mkoryak** [comment]
Looks like a regression that happened sometime after 2015 :) 
It was never really right in 2015 either, but it does work a bit better:

http://jsfiddle.net/gxtjLw79/1/

I will see what I can do to fix it

**Comment by mkoryak** [comment]
Fixed it, but only in 'absolute' position mode. This code was written by some junior engineer and is hard to work with, so I will not fix it for 'fixed'. 
http://jsfiddle.net/1b64qy8p/

I cut and pushed a new release to npm

**Comment by mkoryak** [comment]
I tagged the wrong issue in my fix, oops.
https://github.com/mkoryak/floatThead/commit/4a6792b7b16bdb69a6862d9da756408a19c9ba5c

**Comment by mkoryak** [comment]
I assume this fixes your issue. Please feel free to reopen this if you find otherwise, or if I broke something else with that fix :)

**Comment by kuanyui** [comment]
> Fixed it, but only in 'absolute' position mode. This code was written by some junior engineer and is hard to work with, so I will not fix it for 'fixed'. http://jsfiddle.net/1b64qy8p/
> 
> I cut and pushed a new release to npm

Issue still exists in the JSFiddle you provided http://jsfiddle.net/1b64qy8p/ with `position: "absolute"`...

https://user-images.githubusercontent.com/1370070/224877744-cdd55088-577e-4705-85cc-af81a12cb934.mp4

> I assume this fixes your issue. Please feel free to reopen this if you find otherwise, or if I broke something else with that fix :)

Sorry I didn't reply on time because 2 days ago JSFiddle's server was down.

And it seems I have no permission to reopen this issue.

**Comment by mkoryak** [comment]
I know this exists, been busy at work
